In [26]:
from numpy import exp, array, random, dot

class NeuralNetwork():
    def __init__(self):
        # seed the random number generator, so it is non random across trials
        random.seed(1)
        
        # assign weights 
        
        self.synaptic_weights = 2*random.random((3, 1)) - 1
    
    def sigmoid(self, x):
        return 1/(1+exp(-x))
    
    def d_sigmoid(self, x):
        return x*(1-x)
    
    def train(self, training_inputs, training_outputs, n_iter):
        for iter in xrange(n_iter):
            output = self.predict(training_inputs)
            
            error = training_outputs - output 
            
            adjustment = dot(training_inputs.T, error*self.d_sigmoid(output))
            
            self.synaptic_weights += adjustment
    
    def predict(self, inputs):
        return self.sigmoid(dot(inputs, self.synaptic_weights))

if __name__ == '__main__':
    
    # single neuron neural network
    neural_net = NeuralNetwork()
    
    print 'Initializing random synaptic weights'
    print neural_net.synaptic_weights
    
    
    # training data; 4 examples, each with 3 input values and 1 output
    
    training_inputs = array([[0,0,1], [1,1,1], [1,0,1], [0,1,0]])
    training_outputs = array([[0,1,1,0]]).T
    
    # train the network:
    neural_net.train(training_inputs, training_outputs, 1000)
    
    print 'new synaptic weights after training:'
    print neural_net.synaptic_weights
    
    print 'predicting on [1,0,0]'
    print neural_net.predict([1,0,0])


Initializing random synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
new synaptic weights after training:
[[ 9.07435607]
 [-2.9736727 ]
 [-2.9719595 ]]
predicting on [1,0,0]
[ 0.99988545]


array([ 1.02661833])